default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  user: gilmar
  password: 050297

development:
  <<: *default
  database: tutorial_dev

test:
  <<: *default
  database: tutorial_test

production:
  <<: *default
  database: <%= ENV['APP_DATABASE_NAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>